db:
  database: DB_DATABASE
  logging:
    __name: DB_LOGGING
    __format: boolean

jwt:
  secretKey: JWT_SECRET_KEY
  expiresIn: JWT_TOKEN_EXPIRATION_TIME
  refreshExpiresIn: JWT_REFRESH_TOKEN_EXPIRATION_TIME

storage:
  awsAccessKeyId: AWS_ACCESS_KEY_ID_CONFIG
  awsSecretAccessKey: AWS_SECRET_ACCESS_KEY_CONFIG
  awsRegion: AWS_REGION_CONFIG
  awsS3Bucket: AWS_S3_ASSET_BUCKET

paymentGateway:
  key: PAYMENT_GATEWAY_KEY
  provider: PAYMENT_GATEWAY_PROVIDER
  frontEndDomain: FRONT_END_DOMAIN
