service:
  port: 3000
  apiBasePath: /api

db:
  type: 'mysql'
  host: 'advent-event.cjnbzcacrkqk.ap-southeast-1.rds.amazonaws.com'
  port: 3306
  username: 'admin'
  password: '=88JgBE%68'
  database: 'advent-event'
  logging: true

jwt:
  secretKey: SuperSecretKey
  expiresIn: 2592000
  refreshExpiresIn: 7776000
